### PR TITLE
refactor checkUtils: remove repeating commands

### PR DESCRIPTION
**Pull request by 4ndrej**
putting checked utils into array and running through the array in for loop cleans the code

### CODE REVIEW

**Comment by tomice** [comment]
Much cleaner! Looks very good. Could you please add the -r flag to the utils variable to make it readonly as well i.e. declare -ar foo=("bar" "baz")

**Comment by 4ndrej** [comment]
changed to read only array

**Comment by tomice** [comment]
Nice, thanks! LGTM

**Comment by arzzen** [comment]
Thanks for your contribution @4ndrej

**Pull request merged**
