### PR TITLE
Add git branch option

### PR DESCRIPTION
**Pull request by treussart**
Adds the possibility to specify the branch to be taken into account for statistics.

### CODE REVIEW

**Comment by tomice** [comment]
Hello, thank you for your contribution! Looking at this commit, it seems very similar to the current JSON option. I tested the output and I get something similar to the following:
```
ice@3900x:git-quick-stats(add_git_branch_option)$ ./git-quick-stats -Z
Which branch? master
 Jess <jessachandler@gmail.com>;32;0%
 Lukas Mestan <lukas.mestan@hyperia.sk>;139;2%
 Pawaer <pawaer@t-online.de>;2;0%
 Jorge Maldonado Ventura <jorgesumle@freakspot.net>;6;0%
 ...
```

Is this the expected outcome? There are no titles for the columns being parsed with this output such as name, email, and so on. If a user were to put this into something that can read a CSV file, they might be a bit confused at first glance due to the lack of "columns" describing what each field is.

This looks like it is using semicolons for its line separator instead of commas. While this is technically valid, I would expect this to be commas first. This brings up the US vs European specs of comma vs semicolon. Verifying locale before generating the list and defining a commonly accepted separator in the region would probably be best. A quick and easy way would be for the user to define how they want their CSV's line separator to be defined as.

If we are going to add a CSV feature, we should probably have it a bit more full featured than the current four fields that it is parsing. In fact, we should probably refactor our entire JSON portion of this and extend it to allow the user to choose between JSON and CSV, then output this accordingly. This way, the user can choose between one or the other file formats they would like their statistics exported as.

I also do not see this added to the interactive menu, and I don't see any updates to the man pages regarding this change. Both of these should be updated to reflect this new change.

The current git commit log message is a bit sparse as to what this does, what the intention is, and what the plan for the future is, too. There was no description added to this pull request, so it is hard to see what the intention of your pull request is. Could you expand on this to see can see what the goal is, as well as future intentions? Thanks!

**Comment by treussart** [comment]
Hi, thanks for your reply, I will cut the PR in half. 
I submitted only the new options :  `_GIT_BRANCH`
This allows me to run the binary without interaction, because without the options the prompt display :  `Which branch?`

**Comment by tomice** [comment]
Tested and works good. However, it is missing newly added functionality to the man pages. Please update the man pages as well to document the new feature.

**Comment by treussart** [comment]
Ok, I added functionality to the man pages.

**Comment by tomice** [comment]
In the man pages, it looks like it is missing a double quote around `master` (or it has a double quote that can be removed). Do you think you could fix this, too, please? Thanks!

**Review by tomice — APPROVED** [review]

**Comment by treussart** [comment]
Sorry it's done.

**Pull request merged**
