### PR TITLE
[Feature Request] Add arrow symbol when accepting input

### PR DESCRIPTION
**Pull request by joshuadeguzman**
**Summary**
- Added arrow symbol (↳) when reading input from the user
- Added `.github` folder for containing GitHub related assets
- Added updated example screenshots
- Referenced README to the raw github content URLs for the screenshots

### CODE REVIEW

**Comment by joshuadeguzman** [comment]
Failed build is caused perhaps by the travis configuration. Let me know your thoughts.

**Comment by tomice** [comment]
The feature(s) are fine. However, I question having image assets showing what the program looks like via a Markdown interpreter (which is usually done via a browser) that are possibly going to change frequently inside of the repo. 

The PNGs will most likely continue to change each time we have a new feature, and these are not easily compressible via git since they are binary object blobs. This means that git operations, such as clone, will increase, as well as the repo size. Rather, I think it is more prudent in the long run to have these solely hosted on GitHub's CDN. 

In the extreme case, it would cause the image links to break when interpreting the Markdown if GitHub is down or there's no access to the Internet. That, to me, is a more of a minor inconvenience and worth dealing with vs the inverse effects of having possibly hundreds of PNGs in git's history that don't do much more than show what the program looks like when viewing this project a few years down the road.

I'm more than welcome to hear a counter argument to this and why placing image assets inside a folder that stays with the repo is a good idea, though. I am simply basing this off of years of experience at my current workplace which tends to have heavily firewall'd and slower Internet connections, as well as having to do everything on SMB shares - both of which increase the length of time it takes for git to perform its operations.

**Comment by tomice** [comment]
Double-checked this feature request. The ↳ symbol appears to be missing from my default font on my WSL instance. It makes me weary that U+21B3 may not be visible on all shell instances by default using certain fonts. There seems to be an ongoing issue with WSL and UTF-8 in general, but it may persist on other, older *nix distros which might not have this symbol immediately available and cause some users to think this could be a bug. A previous pull request is utilizing the > symbol as an alternative which is available in ASCII and other character encoding standards. Thoughts?
arrow_issue

**Comment by joshuadeguzman** [comment]
Thanks for looking into this, will have to check a viable character for this PR.

**Comment by joshuadeguzman** [comment]
Good point, but let me check how far I could optimize the images to conform with slow networks. Otherwise, will remove it and lean towards Github's CDN urls generate here automagically. :)

**Comment by tomice** [comment]
The layout and presentation of this pull request was great, and there were some solid features suggested in here. Thank you! :) 

However, I'm going to close this pull request for now for a few reasons. Normally, the .github folder is for issues and pull request templates, so I'm not sure if this is the appropriate place for images (if it is, feel free to reference documentation as I'm more than happy to revert my decision). The other is the Unicode issue mentioned earlier when I ran this in WSL. #65 has a good alternative solution to the Unicode issue, in my opinion, and I think we will go with that because the greater than symbol (>) is an ASCII symbol and backwards compatible with almost all character encoding sets.

**Pull request closed without merging**
