### PR TITLE
POSIX shell conversion

### PR DESCRIPTION
**Pull request by mcpcpc**
### Objective

Scrub "bashisms" for more cross-platform and shell compatibility

### Conversion Progress

- [x] current remaining output of `shellcheck -s sh -f gcc`:
```
git-quick-stats:456:77: note: Double quote to prevent globbing and word splitting. [SC2086]
git-quick-stats:602:15: warning: Use var=$(command) to assign output (or quote to assign string). [SC2209]
git-quick-stats:605:41: note: Double quote to prevent globbing and word splitting. [SC2086]
git-quick-stats:605:55: note: Double quote to prevent globbing and word splitting. [SC2086]
```

### Functionality Check

- [x] Contribution stats (by author)
- [x] Contribution stats (by author) on a specific branch
- [x] Git changelogs (last 10 days)
- [x] Git changelogs by author
- [x] My daily status
- [x] Save git log output in JSON format
- [x] Branch tree view (last 10)
- [x]  All branches (sorted by most recent commit)
- [x] All contributors (sorted by name)
- [x] Git commits per author
- [x] Git commits per date
- [x] Git commits per month
- [x] Git commits per weekday
- [x] Git commits per hour
- [x] Git commits per author per hour
- [x] Code reviewers (based on git history)
- [x] Non-interactive usage

### References

- https://mywiki.wooledge.org/Bashism

### CODE REVIEW

**Comment by mcpcpc** [comment]
probably needs some additional cleanup.  But i figured it would be best to move out of draft to start the review process.

**Comment by tomice** [comment]
Thanks for your contribution! Looking at this change is somewhat difficult given the amount of refactoring that has gone on. I don't really have any POSIX-only environments anymore, so I can't attest to this working in a fully POSIX env. It also kinda removes some of the safeties that Bash provides (safely encapsulating vars in local scope without them leaking globally, for example). Part of me feels this should be a fork given how much of a drastic change it is.

That said, I found the following issues:

* The date field "last commit" when selecting "Contribution stats (by author)" is blank
* A newline isn't being added properly when selecting "Git changelogs (last 10 days)"
* Some of the spacing is different with regards to the title text (red bold text) and the body text in certain areas (All Contributors sorted by last name is one example, but it kinda occurs throughout everything)
* Git commits per hour is broken compared to original functionality
* Git commits by author per hour appears to be broken (shows nothing when I insert my name)
* I'm not entirely sure why `readonly `was removed. I believe `readonly `is a POSIX-compliant attribute, where as declare -r is a Bash-ism.

One style issue I have is that there are a lot of commits and the commits don't really say what's going on, either, making this somewhat harder to review. For example, it's hard to tell what "cleanup" and "oops..." are doing at first glance. I believe we have some overall guidelines written here to help out with direction regarding that: https://github.com/arzzen/git-quick-stats#contribution

Finally, if we go through with this change, that means that all changes from here on out must be POSIX-compliant. Otherwise, it kinda negates the work being done here. Unfortunately, I am not well-versed in strictly POSIX-style programming, so if we want to adhere to that, we will need more rigorous tests that enforce POSIX-only coding styles. Preferably something more than a simple static analysis check like shellcheck.

**Comment by mcpcpc** [comment]
Thank you for the detailed response. Ultimately, your points are all valid. I think I got ahead of myself when i started refactoring and ended up breaking more in the process.  I also did not check the guidelines beforehand.  Regarding POSIX-compliance, I imagine this might take some time to do.. so the title of this PR is miss-leading. 

I will close this PR now.  Future PRs will comply with the guidelines and be easier to review and verify.  i can also provide further explanation of the changes i have made.

**Comment by tomice** [comment]
Please don’t get discouraged because of the comments I made. I’d love to see this work continued. My recommendation would be to create a POSIX fork of this first, and we can try to include some of that work in this codebase. 

For example, the printf stuff is great and should be favored instead of echo. There are other sections of your PR that improve this codebase’s overall compatibility across shells, too.

So, my recommendation would be to work on it on the side, maybe build some solid tests (we are in desperate need of good tests), refactor areas that make sense, change things to be more compatible across all shells like you’re currently doing, and we can start to include those in this codebase. Again, this is really good work, and it’s worth pursuing if you have the time. :)

**Pull request closed without merging**
