### PR TITLE
Improve the interactive menu

### PR DESCRIPTION
**Pull request by Calinou**
This adds a `>` at the end of the message to denote the program is waiting for user input.

This also tweaks colors for better readability.

## Preview

Preview

### CODE REVIEW

**Comment by tomice** [comment]
TravisCI checks aside, LGTM. Tested on RHEL 7.x and CentOS environments. Example pictures should be updated if this pull request is approved to reflect the new menu changes.

**Comment by tomice** [comment]
Going back to this for a bit since it hasn't been merged in yet, and I'd like to include it. I started testing it on different terminal window themes, and on light themes, the cyan gets a bit washed out. In the currently implemented theme, the yellow tends to get washed out on light themes. So I started thinking about how we could possibly add different themes for people, as it could help greatly with accessibility and people who have issues seeing certain colors.

I was thinking it could just be a global variable a user can set akin to how we are already doing it with _GIT_SINCE and _GIT_UNTIL. Example code I'm thinking of in my head on how it could work:

```sh
function show_menu() {
    local normal=$(tput sgr0)
    local bold=$(tput bold)
    local cyan=$(tput setaf 6)
    local red=$(tput setaf 1)
    local yellow=$(tput setaf 3)
    local white=$(tput setaf 7)
    local titles=""
    local text=""
    local nums=""
    local help_txt=""

    if [[ "${THEME}" == "light" ]]; then
        titles="${cyan}"
        text="${white}"
        nums="${bold}"
        help_txt="${cyan}"
    else
        titles="${red}"
        text="${white}"
        nums="${yellow}"
        help_txt="${white}"
    fi
   
    echo -e "\n${titles} Generate: ${normal}"
    echo -e "${nums}   1)${text} Contribution stats (by author) ${normal}"
    echo -e "${nums}   2)${text} Git changelogs (last $_limit days) ${normal}"
    echo -e "${nums}   3)${text} Git changelogs by author ${normal}"
    echo -e "${nums}   4)${text} My daily status ${normal}"
    echo -e "${titles} List: ${normal}"
    echo -e "${nums}   5)${text} Branch tree view (last $_limit)${normal}"
    echo -e "${nums}   6)${text} All branches (sorted by most recent commit) ${normal}"
    echo -e "${nums}   7)${text} All contributors (sorted by name) ${normal}"
    echo -e "${nums}   8)${text} Git commits per author ${normal}"
    echo -e "${nums}   9)${text} Git commits per date ${normal}"
    echo -e "${nums}  10)${text} Git commits per month ${normal}"
    echo -e "${nums}  11)${text} Git commits per weekday ${normal}"
    echo -e "${nums}  12)${text} Git commits per hour ${normal}"
    echo -e "${nums}  13)${text} Git commits by author per hour ${normal}"
    echo -e "${titles} Suggest: ${normal}"
    echo -e "${nums}  14)${text} Code reviewers (based on git history) ${normal}"
    echo -e "\n${help_txt}Please enter a menu option or ${bold}press enter to exit. ${normal}"
    read -r opt
}
```

We could then update the documentation and possibly add screenshots to show different themes available to the user. Thoughts?

**Comment by Calinou** [comment]
@tomice Sounds good to me. Unfortunately, there's no real standard I know of when it comes to setting application-specific themes in CLI applications. Detecting the background color is possible, but it's not particularly trivial (see https://github.com/vim/vim/issues/869).

**Comment by tomice** [comment]
I think the two themes (current one and the proposed one in this PR) would be sufficient for a basic implementation at the moment. If more users would like to see this expanded, be made more intelligent by detecting current terminal colors, and whatnot, then I may further investigate on how something more complex could be implemented. Or someone who might already know could make a PR and do it, as well.

**Comment by tomice** [comment]
Let me know your thoughts on this latest commit I just pushed to your fork @Calinou and if it looks okay to you.

**Comment by Calinou** [comment]
The default theme's text appears darker, is this intended?

## Default theme

image

## Alternative theme

image

**Comment by tomice** [comment]
I redid it with another terminal application on a different system as WSL isn't showing me the full color range of tput. I think they're closer now, but if you got a moment, could you double-check to make sure everything looks okay?

**Comment by Calinou** [comment]
The alternative theme looks good now, but the default theme's colors look all over the place to me. The main intent of my PR was to use less distracting colors (and avoiding red/yellow as these tend to be used for errors and warnings).

**Comment by tomice** [comment]
When you say that the colors are "all over the place," do you mean that there is an extreme diversion from the original theme vs the one in this modified PR, or do you just vastly prefer the alternative theme to the original theme? I'm having a hard time following where there are issues at the moment. Here is what the default theme looks like on OS X for me:
osxTheme

Here is what the default theme looks like in WSL for me:
modifiedOnWSL

And here is the original theme from v2.0.4:
originalTheme

I now see there's an issue with "Suggest:" having a weird looking colon after it after reviewing these screenshots. The white help text (Please enter a menu option...) was intentional, but that can be changed to be more akin to how the original theme if feel it is too much of a diversion and makes things look too weird.

**Comment by Calinou** [comment]
> When you say that the colors are "all over the place," do you mean that there is an extreme diversion from the original theme vs the one in this modified PR, or do you just vastly prefer the alternative theme to the original theme?

I meant the latter :slightly_smiling_face:

**Comment by tomice** [comment]
Newly proposed theme now the default theme. In order to go back to the old theme, _MENU_THEME will need to be set to legacy for those who prefer it. It's hard to say if users will prefer this or not since we don't have any A/B testing, but your comment on leaving red text exclusive for errors is a solid reason for experimenting with other color schemes, IMO. Double-check everything and make sure it looks kosher if you got a moment.

**Comment by Calinou** [comment]
Looks good to me! Thanks :smiley:

**Comment by vcunat** [comment]
I tried 2.0.8 now, and the colors are very unsuitable for light-themed terminals, apparently.  For my default the menu options have exactly the same color of text and background.  With xterm it's not as bad, but still not well usable.

**Comment by Calinou** [comment]
@vcunat Shouldn't light terminal themes display white colors as black (and vice versa)?

**Comment by vcunat** [comment]
I have no idea how colors on terminals work :woman_shrugging:

**Comment by tomice** [comment]
In the README.md, there is a section on color themes. It shows how to revert back to the original theme should you wish to do so. You can put this in your .bashrc if it is something you would like all of the time.

**Pull request merged**
